### ISSUE TITLE
XD Framework

### ISSUE THREAD

**Issue by Alvazz** [top-master/QImageConverter#1]
Hi,  https://bitbucket.org/top-master/xd/src/master this link can not found!

**Comment by top-master** [comment]
You can now use XD5 from: [github.com/top-master/XD](https://github.com/top-master/XD)

The version 4 was not published due to license complications.

**However,** this repo didn't use any of the many XD-only features, hence even in the past you could (with little change) build this repo with Qt5 instead of XD4.
